In [1]:
import pickle
with open('0404_result_data.pkl',"rb") as fr:
    data = pickle.load(fr)
data

,sentiment_x,temp+eda,mfcc,text_tokenize,Temp,EDA
0,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.36212430820312924, 0.5950855218071341, 0.6...","[8, 5, 7, 276, 35, 2, 13, 723, 22, 280, 13, 84...","[34.81, 34.81, 34.81, 34.79, 34.79, 34.79, 34....","[2.856493, 2.788578, 2.678377, 2.652749, 2.645..."
1,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.09967221317831643, 0.46074755225157077, 0....","[137, 253, 31, 1042, 34, 845, 104, 1166, 979, ...","[34.79, 34.79, 34.79, 34.77, 34.77, 34.77, 34....","[2.647035, 2.653442, 2.631658, 2.614999, 2.623..."
2,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.5217207684902612, 0.7059450474628848, 0.63...","[7, 44, 99, 17, 49, 749, 82, 228, 6, 3, 2976, ...","[34.75, 34.75, 34.75, 34.75, 34.79, 34.79, 34....","[2.896217, 2.975664, 3.02692, 3.071769, 3.0922..."
3,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.013638213363584173, 0.4977522798008912, 0....","[99, 93, 35, 61, 262, 1, 723, 2179, 25, 2517, ...","[34.77, 34.77, 34.77, 34.77, 34.77, 34.77, 34....","[3.689019, 3.692863, 3.659546, 3.409672, 3.123..."
4,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.1814917031611868, 0.5011223135638304, 0.14...","[15, 79, 16, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[34.55, 34.55, 34.55, 34.55, 34.55, 34.55, 34....","[4.412055, 4.536246, 4.630991, 4.669401, 4.661..."
...,...,...,...,...,...,...
12688,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.0, 0.44890249617394556, 0.4151811098070448...","[96, 11, 65, 42, 258, 14989, 2, 240, 684, 2, 2...","[35.07, 35.07, 35.07, 35.07, 35.05, 35.05, 35....","[1.194537, 1.171473, 1.150971, 1.129189, 1.106..."
12689,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.2285113780573238, 0.779642897290782, 0.457...","[3, 504, 494, 3, 4030, 800, 298, 0, 0, 0, 0, 0...","[35.05, 35.05, 35.07, 35.07, 35.07, 35.07, 35....","[0.929301, 0.922894, 0.917769, 0.916488, 0.912..."
12690,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.0, 0.3924988321574137, 0.6015662496016466,...","[14, 65, 58, 14990, 164, 33, 1346, 2438, 11, 2...","[35.05, 35.05, 35.05, 35.05, 35.05, 35.05, 35....","[0.888298, 0.88061, 0.878048, 0.875485, 0.8742..."
12691,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.0, 0.404710343900125, 0.6941450242437002, ...","[307, 20, 1533, 17, 1432, 63, 27, 1, 74, 47, 0...","[35.05, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[0.83192, 0.825513, 0.821669, 0.82295, 0.81910..."
12692,0,"[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[[0.07021882960247872, 0.2635582968035488, 0.6...","[94, 20, 628, 12, 6064, 51, 219, 2990, 374, 0,...","[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[0.797324, 0.794761, 0.796043, 0.794761, 0.792..."

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow import nn
import pandas as pd
import numpy as np

In [3]:
from imblearn.over_sampling import SMOTE

## DATA augmentation

In [4]:
data = data[['sentiment_x', 'EDA']]

In [5]:
data

       sentiment_x                                                EDA
0                0  [2.856493, 2.788578, 2.678377, 2.652749, 2.645...
1                0  [2.647035, 2.653442, 2.631658, 2.614999, 2.623...
2                0  [2.896217, 2.975664, 3.02692, 3.071769, 3.0922...
3                0  [3.689019, 3.692863, 3.659546, 3.409672, 3.123...
4                0  [4.412055, 4.536246, 4.630991, 4.669401, 4.661...
...            ...                                                ...
12688            0  [1.194537, 1.171473, 1.150971, 1.129189, 1.106...
12689            0  [0.929301, 0.922894, 0.917769, 0.916488, 0.912...
12690            0  [0.888298, 0.88061, 0.878048, 0.875485, 0.8742...
12691            0  [0.83192, 0.825513, 0.821669, 0.82295, 0.81910...
12692            0  [0.797324, 0.794761, 0.796043, 0.794761, 0.792...

[12693 rows x 2 columns]

In [6]:
list_col = data['EDA']
list_col_array = np.array(list_col.tolist())
EDA_new = pd.DataFrame(list_col_array, columns=[f'col{i+1}' for i in range(list_col_array.shape[1])])

In [7]:
EDA_new

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80
0,2.856493,2.788578,2.678377,2.652749,2.645061,2.618151,2.606618,2.481040,2.431066,2.385627,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.647035,2.653442,2.631658,2.614999,2.623969,2.472763,2.340778,2.294647,2.427914,2.436884,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.896217,2.975664,3.026920,3.071769,3.092272,3.116619,3.139684,3.130714,3.084584,2.983352,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.689019,3.692863,3.659546,3.409672,3.123918,2.976556,2.906078,2.747573,2.807800,2.768076,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4.412055,4.536246,4.630991,4.669401,4.661719,4.654037,4.598982,4.543929,4.510640,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688,1.194537,1.171473,1.150971,1.129189,1.106125,1.093311,1.075373,1.056153,1.043339,1.053590,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12689,0.929301,0.922894,0.917769,0.916488,0.912644,0.903674,0.903674,0.898549,0.892142,0.887017,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12690,0.888298,0.880610,0.878048,0.875485,0.874204,0.867797,0.866516,0.867797,0.858828,0.857546,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12691,0.831920,0.825513,0.821669,0.822950,0.819107,0.816544,0.813981,0.815262,0.806293,0.805012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12692,0.797324,0.794761,0.796043,0.794761,0.792199,0.792199,0.790917,0.784511,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
result = pd.concat([EDA_new, data['sentiment_x']], axis=1)

In [9]:
result

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col72,col73,col74,col75,col76,col77,col78,col79,col80,sentiment_x
0,2.856493,2.788578,2.678377,2.652749,2.645061,2.618151,2.606618,2.481040,2.431066,2.385627,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,2.647035,2.653442,2.631658,2.614999,2.623969,2.472763,2.340778,2.294647,2.427914,2.436884,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,2.896217,2.975664,3.026920,3.071769,3.092272,3.116619,3.139684,3.130714,3.084584,2.983352,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,3.689019,3.692863,3.659546,3.409672,3.123918,2.976556,2.906078,2.747573,2.807800,2.768076,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,4.412055,4.536246,4.630991,4.669401,4.661719,4.654037,4.598982,4.543929,4.510640,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688,1.194537,1.171473,1.150971,1.129189,1.106125,1.093311,1.075373,1.056153,1.043339,1.053590,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12689,0.929301,0.922894,0.917769,0.916488,0.912644,0.903674,0.903674,0.898549,0.892142,0.887017,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12690,0.888298,0.880610,0.878048,0.875485,0.874204,0.867797,0.866516,0.867797,0.858828,0.857546,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12691,0.831920,0.825513,0.821669,0.822950,0.819107,0.816544,0.813981,0.815262,0.806293,0.805012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12692,0.797324,0.794761,0.796043,0.794761,0.792199,0.792199,0.790917,0.784511,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [10]:
result = result.apply(pd.to_numeric, errors='coerce')

In [11]:
value_counts = result['sentiment_x'].value_counts()

In [12]:
print(value_counts)

0    10508
1     1428
2      214
3      209
4      177
5       99
6       58
Name: sentiment_x, dtype: int64

In [13]:
selected_rows = result[result['sentiment_x'].isin([1,2,3,4,5,6])]

In [14]:
selected_zero = result[result['sentiment_x'].isin([0])]

In [15]:
selected_zero

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col72,col73,col74,col75,col76,col77,col78,col79,col80,sentiment_x
0,2.856493,2.788578,2.678377,2.652749,2.645061,2.618151,2.606618,2.481040,2.431066,2.385627,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,2.647035,2.653442,2.631658,2.614999,2.623969,2.472763,2.340778,2.294647,2.427914,2.436884,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,2.896217,2.975664,3.026920,3.071769,3.092272,3.116619,3.139684,3.130714,3.084584,2.983352,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,3.689019,3.692863,3.659546,3.409672,3.123918,2.976556,2.906078,2.747573,2.807800,2.768076,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,4.412055,4.536246,4.630991,4.669401,4.661719,4.654037,4.598982,4.543929,4.510640,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688,1.194537,1.171473,1.150971,1.129189,1.106125,1.093311,1.075373,1.056153,1.043339,1.053590,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12689,0.929301,0.922894,0.917769,0.916488,0.912644,0.903674,0.903674,0.898549,0.892142,0.887017,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12690,0.888298,0.880610,0.878048,0.875485,0.874204,0.867797,0.866516,0.867797,0.858828,0.857546,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12691,0.831920,0.825513,0.821669,0.822950,0.819107,0.816544,0.813981,0.815262,0.806293,0.805012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12692,0.797324,0.794761,0.796043,0.794761,0.792199,0.792199,0.790917,0.784511,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [16]:
n_samples = 5000
selected_zero_sample = selected_zero.sample(n=n_samples)

In [17]:
selected_zero_sample

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col72,col73,col74,col75,col76,col77,col78,col79,col80,sentiment_x
3816,1.461440,1.465284,1.467847,1.467847,1.466565,1.458877,1.460158,1.457596,1.461440,1.461440,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
8860,1.623881,1.621319,1.623881,1.623881,1.623881,1.616194,1.614912,1.621319,1.623881,1.625163,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
7496,0.692800,0.691519,0.691519,0.694080,0.690239,0.690239,0.686399,0.688959,0.688959,0.690239,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1502,6.293591,6.533199,6.719848,6.772382,6.773664,6.748037,6.846700,7.042743,7.331831,7.422805,...,7.079902,7.466371,7.605457,7.577268,7.442729,7.103176,6.768748,6.404147,6.225254,0
729,10.465914,10.419785,10.362125,10.323686,10.298059,10.268588,10.242962,10.237837,10.283964,10.385190,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4701,0.344678,0.345959,0.342115,0.342115,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
6725,0.513814,0.513814,0.513814,0.512532,0.509970,0.509970,0.512532,0.513814,0.513814,0.509970,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4665,0.338271,0.338271,0.338271,0.338271,0.338271,0.336990,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1340,3.449395,3.459646,3.469898,3.580099,3.760777,3.931205,4.061908,4.143169,4.159827,4.131636,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
879,8.926584,8.727966,8.885579,9.071383,9.097012,9.100856,9.098293,8.945806,8.861233,8.853544,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0

In [18]:
selected_rows

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col72,col73,col74,col75,col76,col77,col78,col79,col80,sentiment_x
7,3.426862,3.425049,3.382762,3.267435,3.269998,3.269998,3.187988,3.328943,3.491682,3.695426,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
8,3.330224,3.353290,3.358415,3.357134,3.368667,3.380199,3.376355,3.395576,3.473742,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
9,3.645451,3.823566,3.986305,4.090631,4.173923,4.125229,4.003495,3.888169,3.725430,3.640857,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
11,3.508340,3.517310,3.641607,3.744119,3.216179,3.581380,3.904295,3.853039,3.818441,3.656983,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
16,5.178960,5.131588,5.105982,5.085496,5.075254,5.071413,5.068852,5.084216,5.080375,5.085496,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12654,0.482047,0.484610,0.478203,0.479485,0.479485,0.474359,0.473078,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
12660,0.605055,0.606336,0.605055,0.602492,0.599930,0.605055,0.601211,0.601211,0.601211,0.597367,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
12671,0.553802,0.556365,0.556365,0.548677,0.553802,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
12673,0.740876,0.731907,0.724219,0.715250,0.711406,0.704999,0.697311,0.697311,0.693467,0.685779,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
12675,0.769065,0.774191,0.761378,0.749846,0.742158,0.734470,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6

In [19]:
smote = SMOTE()

In [20]:
X = selected_rows.drop(['sentiment_x'], axis=1).values
y = selected_rows['sentiment_x'].values

In [21]:
smote = SMOTE(sampling_strategy={1:5000,2: 5000, 3: 5000, 4: 5000, 5: 5000, 6: 5000},random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

C:\Users\pc\anaconda3\lib\site-packages\imblearn\utils\_validation.py:313: UserWarning: After over-sampling, the number of samples (5000) in class 1 will be larger than the number of samples in the majority class (class #1 -> 1428)
  warnings.warn(
C:\Users\pc\anaconda3\lib\site-packages\imblearn\utils\_validation.py:313: UserWarning: After over-sampling, the number of samples (5000) in class 2 will be larger than the number of samples in the majority class (class #1 -> 1428)
  warnings.warn(
C:\Users\pc\anaconda3\lib\site-packages\imblearn\utils\_validation.py:313: UserWarning: After over-sampling, the number of samples (5000) in class 3 will be larger than the number of samples in the majority class (class #1 -> 1428)
  warnings.warn(
C:\Users\pc\anaconda3\lib\site-packages\imblearn\utils\_validation.py:313: UserWarning: After over-sampling, the number of samples (5000) in class 4 will be larger than the number of samples in the majority class (class #1 -> 1428)
  warnings.warn(
C:\Users\pc\anaconda3\lib\site-packages\imblearn\utils\_validation.py:313: UserWarning: After over-sampling, the number of samples (5000) in class 5 will be larger than the number of samples in the majority class (class #1 -> 1428)
  warnings.warn(
C:\Users\pc\anaconda3\lib\site-packages\imblearn\utils\_validation.py:313: UserWarning: After over-sampling, the number of samples (5000) in class 6 will be larger than the number of samples in the majority class (class #1 -> 1428)
  warnings.warn(

In [22]:
X_resampled

array([[3.426862  , 3.425049  , 3.382762  , ..., 0.        , 0.        ,
        0.        ],
       [3.330224  , 3.35329   , 3.358415  , ..., 0.        , 0.        ,
        0.        ],
       [3.645451  , 3.823566  , 3.986305  , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.49724821, 0.49965278, 0.49387925, ..., 0.        , 0.        ,
        0.        ],
       [8.9898465 , 8.92896579, 8.88314973, ..., 0.        , 0.        ,
        0.        ],
       [1.35837609, 1.38544199, 1.42313852, ..., 0.        , 0.        ,
        0.        ]])

In [23]:
X_resampled.shape

(30000, 80)

In [24]:
y_resampled_df = pd.DataFrame(y_resampled, columns=['sentiment_x'])

In [25]:
df = pd.DataFrame(np.zeros((1, 80)), columns=['col'+str(i) for i in range(1, 81)])

In [26]:
df

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
X_resampled_df = pd.DataFrame(X_resampled, columns=df.columns)

In [28]:
X_resampled_df

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80
0,3.426862,3.425049,3.382762,3.267435,3.269998,3.269998,3.187988,3.328943,3.491682,3.695426,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3.330224,3.353290,3.358415,3.357134,3.368667,3.380199,3.376355,3.395576,3.473742,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.645451,3.823566,3.986305,4.090631,4.173923,4.125229,4.003495,3.888169,3.725430,3.640857,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.508340,3.517310,3.641607,3.744119,3.216179,3.581380,3.904295,3.853039,3.818441,3.656983,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.178960,5.131588,5.105982,5.085496,5.075254,5.071413,5.068852,5.084216,5.080375,5.085496,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,8.747865,8.732689,8.709726,8.687854,8.674133,8.667984,8.657863,8.628840,8.627385,8.628378,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29996,7.432891,7.444371,7.439300,7.439300,7.436293,7.437574,0.843731,0.844177,0.843731,0.841504,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29997,0.497248,0.499653,0.493879,0.494686,0.494369,0.490510,0.488913,0.074297,0.074297,0.073822,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29998,8.989847,8.928966,8.883150,8.837275,8.794548,8.774337,8.757184,8.738708,8.720553,8.719788,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29999,1.358376,1.385442,1.423139,1.470384,1.509363,1.527180,1.521374,1.515168,1.500894,1.482096,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
data_augmented = pd.concat([X_resampled_df, y_resampled_df], axis=1)

In [30]:
data_augmented

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col72,col73,col74,col75,col76,col77,col78,col79,col80,sentiment_x
0,3.426862,3.425049,3.382762,3.267435,3.269998,3.269998,3.187988,3.328943,3.491682,3.695426,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,3.330224,3.353290,3.358415,3.357134,3.368667,3.380199,3.376355,3.395576,3.473742,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,3.645451,3.823566,3.986305,4.090631,4.173923,4.125229,4.003495,3.888169,3.725430,3.640857,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,3.508340,3.517310,3.641607,3.744119,3.216179,3.581380,3.904295,3.853039,3.818441,3.656983,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,5.178960,5.131588,5.105982,5.085496,5.075254,5.071413,5.068852,5.084216,5.080375,5.085496,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,8.747865,8.732689,8.709726,8.687854,8.674133,8.667984,8.657863,8.628840,8.627385,8.628378,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
29996,7.432891,7.444371,7.439300,7.439300,7.436293,7.437574,0.843731,0.844177,0.843731,0.841504,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
29997,0.497248,0.499653,0.493879,0.494686,0.494369,0.490510,0.488913,0.074297,0.074297,0.073822,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
29998,8.989847,8.928966,8.883150,8.837275,8.794548,8.774337,8.757184,8.738708,8.720553,8.719788,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
29999,1.358376,1.385442,1.423139,1.470384,1.509363,1.527180,1.521374,1.515168,1.500894,1.482096,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6

In [31]:
data_augmented = pd.concat([data_augmented, selected_zero_sample ], axis=0)

In [32]:
data_augmented

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col72,col73,col74,col75,col76,col77,col78,col79,col80,sentiment_x
0,3.426862,3.425049,3.382762,3.267435,3.269998,3.269998,3.187988,3.328943,3.491682,3.695426,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,3.330224,3.353290,3.358415,3.357134,3.368667,3.380199,3.376355,3.395576,3.473742,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,3.645451,3.823566,3.986305,4.090631,4.173923,4.125229,4.003495,3.888169,3.725430,3.640857,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,3.508340,3.517310,3.641607,3.744119,3.216179,3.581380,3.904295,3.853039,3.818441,3.656983,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,5.178960,5.131588,5.105982,5.085496,5.075254,5.071413,5.068852,5.084216,5.080375,5.085496,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4701,0.344678,0.345959,0.342115,0.342115,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
6725,0.513814,0.513814,0.513814,0.512532,0.509970,0.509970,0.512532,0.513814,0.513814,0.509970,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4665,0.338271,0.338271,0.338271,0.338271,0.338271,0.336990,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1340,3.449395,3.459646,3.469898,3.580099,3.760777,3.931205,4.061908,4.143169,4.159827,4.131636,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
879,8.926584,8.727966,8.885579,9.071383,9.097012,9.100856,9.098293,8.945806,8.861233,8.853544,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [33]:
column_names = [f'col{i}' for i in range(1, 81)]

# 각 로우의 col1부터 col80까지의 값들을 리스트 형식으로 Temp 열에 저장합니다.
data_augmented['EDA'] = data_augmented[column_names].values.tolist()

In [34]:
data_augmented.head()

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col73,col74,col75,col76,col77,col78,col79,col80,sentiment_x,EDA
0,3.426862,3.425049,3.382762,3.267435,3.269998,3.269998,3.187988,3.328943,3.491682,3.695426,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,"[3.426862, 3.425049, 3.382762, 3.267435, 3.269..."
1,3.330224,3.353290,3.358415,3.357134,3.368667,3.380199,3.376355,3.395576,3.473742,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,"[3.330224, 3.35329, 3.358415, 3.357134, 3.3686..."
2,3.645451,3.823566,3.986305,4.090631,4.173923,4.125229,4.003495,3.888169,3.725430,3.640857,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,"[3.645451, 3.823566, 3.986305, 4.090631, 4.173..."
3,3.508340,3.517310,3.641607,3.744119,3.216179,3.581380,3.904295,3.853039,3.818441,3.656983,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,"[3.50834, 3.51731, 3.641607, 3.744119, 3.21617..."
4,5.178960,5.131588,5.105982,5.085496,5.075254,5.071413,5.068852,5.084216,5.080375,5.085496,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,"[5.17896, 5.131588, 5.105982, 5.085496, 5.0752..."

In [35]:
data = data_augmented[['sentiment_x','EDA']]

In [36]:
data

      sentiment_x                                                EDA
0               1  [3.426862, 3.425049, 3.382762, 3.267435, 3.269...
1               1  [3.330224, 3.35329, 3.358415, 3.357134, 3.3686...
2               1  [3.645451, 3.823566, 3.986305, 4.090631, 4.173...
3               1  [3.50834, 3.51731, 3.641607, 3.744119, 3.21617...
4               1  [5.17896, 5.131588, 5.105982, 5.085496, 5.0752...
...           ...                                                ...
4701            0  [0.344678, 0.345959, 0.342115, 0.342115, 0.0, ...
6725            0  [0.513814, 0.513814, 0.513814, 0.512532, 0.509...
4665            0  [0.338271, 0.338271, 0.338271, 0.338271, 0.338...
1340            0  [3.449395, 3.459646, 3.469898, 3.580099, 3.760...
879             0  [8.926584, 8.727966, 8.885579, 9.071383, 9.097...

[35000 rows x 2 columns]

## 여기부터 시작

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(data[['EDA']], data['sentiment_x'], test_size=0.2, shuffle=True, random_state=4)
x_valid, x_test, y_valid, y_test = train_test_split(x_valid, y_valid, test_size=0.5, shuffle=True, random_state=4)
x_train

                                                     EDA
16169  [14.51882306492956, 14.49297299713034, 14.4570...
10581  [5.107026967557397, 5.031873998404136, 4.96440...
27361  [8.40007491755971, 8.38806229648327, 8.3889335...
15427  [15.987325284139951, 15.880514481205553, 15.84...
1331   [1.293298, 1.293298, 1.289454, 1.284329, 1.285...
...                                                  ...
23346  [0.48057459580882733, 0.4774126136163884, 0.48...
11863  [6.233317788177283, 6.214405581681639, 6.19818...
27063  [4.172138491139187, 4.181352669710672, 4.20966...
8366   [4.373410481346166, 4.375790045832701, 4.37908...
17530  [14.43246917546221, 14.410624882366358, 14.422...

[28000 rows x 1 columns]

In [38]:
print(x_train.shape, x_valid.shape, y_train.shape, y_valid.shape)
print(x_test.shape,y_valid.shape, y_test.shape)

(28000, 1) (3500, 1) (28000,) (3500,)
(3500, 1) (3500,) (3500,)

In [39]:
x_test

                                                     EDA
10537  [1.9215722886540216, 1.925030184931516, 1.9230...
146    [3.336832, 3.450885, 3.746908, 3.836612, 3.840...
7577   [1.5892328922090455, 1.5803893956375845, 1.581...
12667  [0.584554, 0.58071, 0.583273, 0.581991, 0.5781...
3507   [8.808000080934923, 8.800129217337126, 8.82501...
...                                                  ...
23316  [3.815792013792518, 3.7549125914645027, 3.6959...
12162  [3.637790465738198, 3.635162390594942, 3.63718...
15640  [1.6708717596068259, 1.671460121349103, 1.6624...
11161  [4.235733294764073, 4.23891325266139, 4.236516...
2883   [13.437468892082183, 13.475493870186195, 13.51...

[3500 rows x 1 columns]

## 트랜스포머

In [40]:
class TransformerBlock(layers.Layer):  #공통적인 트랜스포머 블럭
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super().__init__()
        self.att = MultiHeadAttention(embedding_dim=embed_dim, num_heads=num_heads)
        self.ffn = keras.Sequential(
            [layers.Dense(ff_dim, activation="relu"), layers.Dense(embed_dim),]
        )
        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = layers.Dropout(rate)
        self.dropout2 = layers.Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs)
        #print('어텐션 후',attn_output.shape)
        attn_output = self.dropout1(attn_output, training=training)
        #print('드롭아웃',attn_output.shape)
        out1 = self.layernorm1(inputs + attn_output)
        #print('레이어놈',out1.shape)
        ffn_output = self.ffn(out1)
        #print('ffn후',ffn_output.shape)
        ffn_output = self.dropout2(ffn_output, training=training)
        print("트랜스포머")
        return self.layernorm2(out1 + ffn_output)
class MultiHeadAttention(tf.keras.layers.Layer): #공통적인 트랜스포머 멀티헤드어텐션
    def __init__(self, embedding_dim, num_heads=4):
        super(MultiHeadAttention, self).__init__()
        self.embedding_dim = embedding_dim # d_model
        self.num_heads = num_heads

        assert embedding_dim % self.num_heads == 0

        self.projection_dim = embedding_dim // num_heads
        self.query_dense = tf.keras.layers.Dense(embedding_dim)
        self.key_dense = tf.keras.layers.Dense(embedding_dim)
        self.value_dense = tf.keras.layers.Dense(embedding_dim)
        self.dense = tf.keras.layers.Dense(embedding_dim)

    def scaled_dot_product_attention(self, query, key, value):
        matmul_qk = tf.matmul(query, key, transpose_b=True)
        depth = tf.cast(tf.shape(key)[-1], tf.float32)
        logits = matmul_qk / tf.math.sqrt(depth)
        attention_weights = tf.nn.softmax(logits, axis=-1)
        output = tf.matmul(attention_weights, value)
        return output, attention_weights

    def split_heads(self, x, batch_size):
        x = tf.reshape(x, (batch_size, -1, self.num_heads, self.projection_dim))
        return tf.transpose(x, perm=[0, 2, 1, 3])

    def call(self, inputs):
        # x.shape = [batch_size, seq_len, embedding_dim]
        batch_size = tf.shape(inputs)[0]

        # (batch_size, seq_len, embedding_dim)
        query = self.query_dense(inputs)
        key = self.key_dense(inputs)
        value = self.value_dense(inputs)

        # (batch_size, num_heads, seq_len, projection_dim)
        query = self.split_heads(query, batch_size)  
        key = self.split_heads(key, batch_size)
        value = self.split_heads(value, batch_size)

        scaled_attention, _ = self.scaled_dot_product_attention(query, key, value)
        # (batch_size, seq_len, num_heads, projection_dim)
        scaled_attention = tf.transpose(scaled_attention, perm=[0, 2, 1, 3])  

        # (batch_size, seq_len, embedding_dim)
        concat_attention = tf.reshape(scaled_attention, (batch_size, -1, self.embedding_dim))
        outputs = self.dense(concat_attention)
        return outputs

In [41]:
from tensorflow.keras.utils import to_categorical #원핫인코딩
y_valid = to_categorical(y_valid)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

## F1-score

In [42]:
from tensorflow.keras import backend as K
def recall(y_target, y_pred):
    # clip(t, clip_value_min, clip_value_max) : clip_value_min~clip_value_max 이외 가장자리를 깎아 낸다
    # round : 반올림한다
    y_target_yn = K.round(K.clip(y_target, 0, 1)) # 실제값을 0(Negative) 또는 1(Positive)로 설정한다
    y_pred_yn = K.round(K.clip(y_pred, 0, 1)) # 예측값을 0(Negative) 또는 1(Positive)로 설정한다

    # True Positive는 실제 값과 예측 값이 모두 1(Positive)인 경우이다
    count_true_positive = K.sum(y_target_yn * y_pred_yn) 

    # (True Positive + False Negative) = 실제 값이 1(Positive) 전체
    count_true_positive_false_negative = K.sum(y_target_yn)

    # Recall =  (True Positive) / (True Positive + False Negative)
    # K.epsilon()는 'divide by zero error' 예방차원에서 작은 수를 더한다
    recall = count_true_positive / (count_true_positive_false_negative + K.epsilon())

    # return a single tensor value
    return recall


def precision(y_target, y_pred):
    # clip(t, clip_value_min, clip_value_max) : clip_value_min~clip_value_max 이외 가장자리를 깎아 낸다
    # round : 반올림한다
    y_pred_yn = K.round(K.clip(y_pred, 0, 1)) # 예측값을 0(Negative) 또는 1(Positive)로 설정한다
    y_target_yn = K.round(K.clip(y_target, 0, 1)) # 실제값을 0(Negative) 또는 1(Positive)로 설정한다

    # True Positive는 실제 값과 예측 값이 모두 1(Positive)인 경우이다
    count_true_positive = K.sum(y_target_yn * y_pred_yn) 

    # (True Positive + False Positive) = 예측 값이 1(Positive) 전체
    count_true_positive_false_positive = K.sum(y_pred_yn)

    # Precision = (True Positive) / (True Positive + False Positive)
    # K.epsilon()는 'divide by zero error' 예방차원에서 작은 수를 더한다
    precision = count_true_positive / (count_true_positive_false_positive + K.epsilon())

    # return a single tensor value
    return precision


def f1score(y_target, y_pred):
    _recall = recall(y_target, y_pred)
    _precision = precision(y_target, y_pred)
    # K.epsilon()는 'divide by zero error' 예방차원에서 작은 수를 더한다
    _f1score = ( 2 * _recall * _precision) / (_recall + _precision+ K.epsilon())
    
    # return a single tensor value
    return _f1score

##  transformer

In [43]:
class temp_TokenAndPositionEmbedding(tf.keras.layers.Layer):
    def __init__(self, max_len, embed_dimm):
        super(temp_TokenAndPositionEmbedding, self).__init__()
        self.temp_emb = tf.keras.layers.Embedding(input_dim=max_len, output_dim=embed_dim)
        self.pos_emb = tf.keras.layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = 80
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.temp_emb(x)
        return x + positions

In [44]:
embed_dim = 32 # Embedding size for each token
num_heads = 4  # Number of attention heads
ff_dim = 32  # Hidden layer size in feed forward network inside transformer
maxlen=50
training=1

temp_input = layers.Input(shape=(80,)) #
temp_embedding_layer = temp_TokenAndPositionEmbedding(80, embed_dim)
temp_embedding = temp_embedding_layer(temp_input)  ########## 

transformer_block = TransformerBlock(32, num_heads, ff_dim) #일단은 블럭 하나만(추후 블럭 여러개 쌓아서 실험도 해보기!)

output = transformer_block(temp_embedding)


x = layers.GlobalAveragePooling1D()(output)
x = layers.Dropout(0.1)(x)
x = layers.Dense(20, activation="relu")(x)
x = layers.Dropout(0.1)(x)

outputs = layers.Dense(7, activation="softmax")(x)  #클래시파이어(분류기)
print(outputs.shape)

model = keras.Model(inputs=temp_input, outputs=outputs)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=['accuracy'])

트랜스포머
(None, 7)

In [45]:
history = model.fit(
    [np.array(x_train['EDA'].to_list())], y_train, batch_size=16, epochs=5, validation_data=([np.array(x_valid['EDA'].to_list())], y_valid)
)

Epoch 1/5
트랜스포머
트랜스포머
1743/1750 [============================>.] - ETA: 0s - loss: 1.9351 - accuracy: 0.1619트랜스포머
1750/1750 [==============================] - 13s 7ms/step - loss: 1.9350 - accuracy: 0.1620 - val_loss: 1.9190 - val_accuracy: 0.1931
Epoch 2/5
1750/1750 [==============================] - 11s 6ms/step - loss: 1.9087 - accuracy: 0.1942 - val_loss: 1.8711 - val_accuracy: 0.2331
Epoch 3/5
1750/1750 [==============================] - 11s 7ms/step - loss: 1.8728 - accuracy: 0.2190 - val_loss: 1.8353 - val_accuracy: 0.2386
Epoch 4/5
1750/1750 [==============================] - 11s 6ms/step - loss: 1.8345 - accuracy: 0.2464 - val_loss: 1.8152 - val_accuracy: 0.2731
Epoch 5/5
1750/1750 [==============================] - 11s 6ms/step - loss: 1.8059 - accuracy: 0.2681 - val_loss: 1.7893 - val_accuracy: 0.2791

In [46]:
print(x_train)

                                                     EDA
16169  [14.51882306492956, 14.49297299713034, 14.4570...
10581  [5.107026967557397, 5.031873998404136, 4.96440...
27361  [8.40007491755971, 8.38806229648327, 8.3889335...
15427  [15.987325284139951, 15.880514481205553, 15.84...
1331   [1.293298, 1.293298, 1.289454, 1.284329, 1.285...
...                                                  ...
23346  [0.48057459580882733, 0.4774126136163884, 0.48...
11863  [6.233317788177283, 6.214405581681639, 6.19818...
27063  [4.172138491139187, 4.181352669710672, 4.20966...
8366   [4.373410481346166, 4.375790045832701, 4.37908...
17530  [14.43246917546221, 14.410624882366358, 14.422...

[28000 rows x 1 columns]

In [47]:
print(y_valid)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]

## 모델 학습

In [48]:
type(x_test)

pandas.core.frame.DataFrame

In [49]:
type(y_test)

numpy.ndarray

In [50]:
type(x_train)

pandas.core.frame.DataFrame

In [51]:
type(x_valid)

pandas.core.frame.DataFrame

In [52]:
x_test_np = np.array(x_test)

In [53]:
x_test_np

array([[list([1.9215722886540216, 1.925030184931516, 1.9230463781839302, 1.9221515572437475, 1.9158410643400459, 1.9143660501474489, 1.911004660966253, 1.9111977504961617, 1.9086347504961616, 1.9059761680625513, 1.9004380332784845, 1.9039924366522776, 1.9037028400260705, 1.9077659606175403, 1.9109081538699546, 1.92166879575032, 1.9202903639913333, 1.9238456920278146, 1.9371684092454917, 1.98258011324898, 2.045763758784121, 2.1059027181631462, 2.158519736010519, 2.179821049854403, 2.195004960324494, 2.1859124221666346, 2.1666114043192617, 2.140518207412072, 2.121726906782377, 2.104533158503138, 2.0863470821874186, 2.0787295582221557, 2.07181291634179, 2.060569588305309, 2.0531711095942042, 2.042700064340046, 2.04340279575032, 2.03977791634179, 2.039295230185674, 2.0298165129679973, 2.024690512967997, 0.16446300888030407, 0.1638837402905784, 0.16417341225409698, 0.1640768298204871, 0.16349763656807248, 0.1629183679783468, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])],
       [list([10.836268, 10.822175, 10.814487, 10.787581, 10.774769, 10.774769, 10.774769, 10.770925, 10.761956, 10.77605, 10.799112, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])],
       [list([1.5892328922090455, 1.5803893956375845, 1.58138898282473, 1.5823893503297422, 1.58395198282473, 1.5733907246918322, 1.5736721375046867, 1.57410867938399, 1.5772633503297422, 0.2179784984314968, 0.21769708561864234, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])],
       ...,
       [list([1.6708717596068259, 1.671460121349103, 1.662490121349103, 1.6572593858931406, 1.6545911914966616, 1.6537928177829764, 1.656943720584737, 1.6562506233864975, 1.6474910942984222, 1.6466922616442203, 1.6460608489084463, 1.646859681562648, 1.6474475843644085, 1.6402417517102068, 1.63356251421685, 1.6355371524745728, 1.636020319820371, 1.6366082226221315, 1.632553751710207, 1.6245930552763332, 1.621924319820371, 1.6241098879305351, 1.6237942226221316, 1.621924319820371, 1.6174494481440802, 1.6133327517102067, 1.6113576545119672, 1.6110854170186104, 1.612156487166169, 1.6135432226221316, 1.6058112537476013, 1.604152280798282, 1.5996141836000426, 1.6032916815626481, 1.6023876545119673, 1.6023876545119673, 1.5987106154898783, 1.5955597126881178, 1.5940060162542444, 1.5956654481440804, 1.5932071836000425, 1.5949718098863575, 1.5927867828356765, 1.5800779772321556, 1.5870111134524838, 1.5850360162542443, 1.5868001836000425, 1.581149047379714, 1.577199311923752, 1.5753729190560049, 1.5739861836000426, 1.5787965182916388, 1.5767161445779538, 1.5769266154898784, 1.5815694481440803, 1.5914247596068258, 1.6107322384153695, 1.6239054136577868, 1.62619617616443, 1.6282760088186317, 1.6357970478407204, 1.6256507832966829, 1.6218685498781151, 1.6169105108560262, 1.606615541981496, 1.6042199618999238, 1.602771541981496, 1.6044304328118484, 1.5998498256795954, 1.6020531914966616, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])],
       [list([4.235733294764073, 4.23891325266139, 4.236516279381631, 4.238622722095539, 4.22981874881578, 4.226058697397624, 4.2358522048898095, 4.2327091437581075, 4.227251090317629, 4.226120861753976, 4.220460917216778, 0.1285059122528025, 0.12742683573865746, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])],
       [list([13.437468892082183, 13.475493870186195, 13.510939174852142, 13.538123334148157, 13.550119028386385, 13.541242050739763, 13.523087124774337, 13.517930052140514, 13.535529957458238, 13.586893231548082, 13.649602808903119, 13.677113693268216, 13.665057010359138, 13.664765909464373, 13.636992435929114, 13.58308210038214, 13.52216280674042, 13.454141567428932, 13.401034368774415, 13.359381508010983, 13.327995707608864, 13.289739634670113, 13.273388095809345, 13.251960285631284, 13.243468570440427, 13.23369643354797, 13.222241360761682, 13.212082191739908, 13.175632762758942, 13.180449814440138, 13.17492303514311, 13.166493656595051, 13.151749530726821, 7.646782483993887, 7.649746841589316, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])]],
      dtype=object)

In [54]:
x_test

                                                     EDA
10537  [1.9215722886540216, 1.925030184931516, 1.9230...
2849   [10.836268, 10.822175, 10.814487, 10.787581, 1...
7577   [1.5892328922090455, 1.5803893956375845, 1.581...
3409   [2.706955, 2.800492, 2.854308, 2.882497, 2.885...
3507   [8.808000080934923, 8.800129217337126, 8.82501...
...                                                  ...
23316  [3.815792013792518, 3.7549125914645027, 3.6959...
12162  [3.637790465738198, 3.635162390594942, 3.63718...
15640  [1.6708717596068259, 1.671460121349103, 1.6624...
11161  [4.235733294764073, 4.23891325266139, 4.236516...
2883   [13.437468892082183, 13.475493870186195, 13.51...

[3500 rows x 1 columns]

In [55]:
list_col = x_test['EDA']

In [56]:
list_col_array = np.array(list_col.tolist())

In [57]:
new_df = pd.DataFrame(list_col_array, columns=[f'col{i+1}' for i in range(list_col_array.shape[1])])

In [58]:
new_df

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80
0,1.921572,1.925030,1.923046,1.922152,1.915841,1.914366,1.911005,1.911198,1.908635,1.905976,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10.836268,10.822175,10.814487,10.787581,10.774769,10.774769,10.774769,10.770925,10.761956,10.776050,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.589233,1.580389,1.581389,1.582389,1.583952,1.573391,1.573672,1.574109,1.577263,0.217978,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.706955,2.800492,2.854308,2.882497,2.885060,2.873528,2.828681,2.790241,2.749239,2.709517,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8.808000,8.800129,8.825011,9.095071,9.469166,1.726322,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3.815792,3.754913,3.695976,3.624759,3.550978,3.468892,3.427672,3.379561,3.343952,3.324307,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3496,3.637790,3.635162,3.637183,3.637250,3.631320,3.630513,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3497,1.670872,1.671460,1.662490,1.657259,1.654591,1.653793,1.656944,1.656251,1.647491,1.646692,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3498,4.235733,4.238913,4.236516,4.238623,4.229819,4.226059,4.235852,4.232709,4.227251,4.226121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3499,13.437469,13.475494,13.510939,13.538123,13.550119,13.541242,13.523087,13.517930,13.535530,13.586893,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
x_test_np = np.array(new_df)

In [60]:
x_test_tensor = tf.convert_to_tensor(x_test_np)

In [61]:
x_test_tensor

<tf.Tensor: shape=(3500, 80), dtype=float64, numpy=
array([[ 1.92157229,  1.92503018,  1.92304638, ...,  0.        ,
         0.        ,  0.        ],
       [10.836268  , 10.822175  , 10.814487  , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.58923289,  1.5803894 ,  1.58138898, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.67087176,  1.67146012,  1.66249012, ...,  0.        ,
         0.        ,  0.        ],
       [ 4.23573329,  4.23891325,  4.23651628, ...,  0.        ,
         0.        ,  0.        ],
       [13.43746889, 13.47549387, 13.51093917, ...,  0.        ,
         0.        ,  0.        ]])>

In [62]:
y_pred = model.predict(x_test_tensor)

트랜스포머
110/110 [==============================] - 1s 4ms/step

In [67]:
y_pred

array([[0.12584116, 0.1527331 , 0.15737382, ..., 0.13344166, 0.08082435,
        0.2604317 ],
       [0.18952248, 0.21701398, 0.13169764, ..., 0.1364675 , 0.06977209,
        0.08269341],
       [0.15044774, 0.15957917, 0.18034545, ..., 0.14099582, 0.09785275,
        0.03768376],
       ...,
       [0.11647467, 0.07586834, 0.24388698, ..., 0.45165625, 0.0876117 ,
        0.01381321],
       [0.16880417, 0.17307113, 0.18161191, ..., 0.12722546, 0.08605946,
        0.05106841],
       [0.1195984 , 0.12978198, 0.13957836, ..., 0.10426193, 0.26209682,
        0.16209058]], dtype=float32)

In [69]:
f1 = f1score(y_test, y_pred)
print('F1 score:', f1)

F1 score: tf.Tensor(0.059847653, shape=(), dtype=float32)

In [64]:
from sklearn.metrics import accuracy_score, precision_score

In [71]:
precision = precision(y_test, y_pred)

In [72]:
print('preicision:', precision)

preicision: tf.Tensor(0.625, shape=(), dtype=float32)

In [73]:
recall = recall(y_test,y_pred)
print('recall:', recall)

recall: tf.Tensor(0.03142857, shape=(), dtype=float32)